import type { BasicSurfaceShape } from './surface';
import type {
  BasicBlock,
  BasicSurface,
  BasicSurfaceOrientation,
  BasicSurfaceRotation,
} from './types';

interface SurfaceDefinition {
  position?: Partial<Vec3>;
  orientation: BasicSurfaceOrientation;
  rotation?: BasicSurfaceRotation;
  shape: BasicSurfaceShape;
}

const BLOCK_SURFACE_DEFINITIONS = {
  block: [
    { orientation: 0, shape: 1 },
    { orientation: 1, shape: 1 },
    { orientation: 2, shape: 1 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, shape: 1 },
  ] as SurfaceDefinition[],
  wedge1: [
    { orientation: 0, rotation: 2, shape: 2 },
    { orientation: 1, rotation: 1, shape: 2 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, rotation: 0, shape: 6 },
  ] as SurfaceDefinition[],
  pyramid1x1: [
    { orientation: 0, rotation: 2, shape: 2 },
    { orientation: 3, rotation: 1, shape: 2 },
    { orientation: 4, rotation: 2, shape: 2 },
    { orientation: 5, rotation: 0, shape: 7 },
  ] as SurfaceDefinition[],
  invpyramid1x1: [
    { orientation: 0, shape: 1 },
    { orientation: 1, rotation: 1, shape: 2 },
    { orientation: 2, rotation: 2, shape: 2 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, rotation: 0, shape: 8 },
    { orientation: 5, rotation: 3, shape: 2 },
  ] as SurfaceDefinition[],
  wedge2: [
    { orientation: 0, rotation: 3, shape: 11 },
    { orientation: 1, rotation: 1, shape: 9 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, rotation: 0, shape: 21 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 12 },
    { position: { z: -1 }, orientation: 1, rotation: 1, shape: 10 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 22 },
  ] as SurfaceDefinition[],
  pyramid1x2: [
    { orientation: 0, rotation: 3, shape: 11 },
    { orientation: 3, rotation: 1, shape: 9 },
    { orientation: 4, rotation: 2, shape: 2 },
    { orientation: 5, rotation: 0, shape: 27 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 12 },
    { position: { z: -1 }, orientation: 3, rotation: 1, shape: 10 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 28 },
  ] as SurfaceDefinition[],
  invpyramid1x2: [
    { orientation: 0, shape: 1 },
    { orientation: 1, rotation: 1, shape: 9 },
    { orientation: 2, rotation: 3, shape: 11 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, rotation: 0, shape: 47 },
    { position: { z: -1 }, orientation: 0, shape: 1 },
    { position: { z: -1 }, orientation: 1, rotation: 1, shape: 10 },
    { position: { z: -1 }, orientation: 2, rotation: 3, shape: 12 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 48 },
    { position: { z: -1 }, orientation: 5, rotation: 3, shape: 2 },
  ] as SurfaceDefinition[],
  wedge4: [
    { orientation: 0, rotation: 3, shape: 17 },
    { orientation: 1, rotation: 1, shape: 13 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, rotation: 0, shape: 23 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 18 },
    { position: { z: -1 }, orientation: 1, rotation: 1, shape: 14 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 24 },
    { position: { z: -2 }, orientation: 0, rotation: 3, shape: 19 },
    { position: { z: -2 }, orientation: 1, rotation: 1, shape: 15 },
    { position: { z: -2 }, orientation: 3, shape: 1 },
    { position: { z: -2 }, orientation: 5, rotation: 0, shape: 25 },
    { position: { z: -3 }, orientation: 0, rotation: 3, shape: 20 },
    { position: { z: -3 }, orientation: 1, rotation: 1, shape: 16 },
    { position: { z: -3 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 5, rotation: 0, shape: 26 },
  ] as SurfaceDefinition[],
  pyramid1x4: [
    { orientation: 0, rotation: 3, shape: 17 },
    { orientation: 3, rotation: 1, shape: 13 },
    { orientation: 4, rotation: 2, shape: 2 },
    { orientation: 5, rotation: 0, shape: 29 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 18 },
    { position: { z: -1 }, orientation: 3, rotation: 1, shape: 14 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 30 },
    { position: { z: -2 }, orientation: 0, rotation: 3, shape: 19 },
    { position: { z: -2 }, orientation: 3, rotation: 1, shape: 15 },
    { position: { z: -2 }, orientation: 5, rotation: 0, shape: 31 },
    { position: { z: -3 }, orientation: 0, rotation: 3, shape: 20 },
    { position: { z: -3 }, orientation: 3, rotation: 1, shape: 16 },
    { position: { z: -3 }, orientation: 5, rotation: 0, shape: 32 },
  ] as SurfaceDefinition[],
  invpyramid1x4: [
    { orientation: 0, shape: 1 },
    { orientation: 1, rotation: 1, shape: 13 },
    { orientation: 2, rotation: 3, shape: 17 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { orientation: 5, rotation: 0, shape: 49 },
    { position: { z: -1 }, orientation: 0, shape: 1 },
    { position: { z: -1 }, orientation: 1, rotation: 1, shape: 14 },
    { position: { z: -1 }, orientation: 2, rotation: 3, shape: 18 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 50 },
    { position: { z: -2 }, orientation: 0, shape: 1 },
    { position: { z: -2 }, orientation: 1, rotation: 1, shape: 15 },
    { position: { z: -2 }, orientation: 2, rotation: 3, shape: 19 },
    { position: { z: -2 }, orientation: 3, shape: 1 },
    { position: { z: -2 }, orientation: 5, rotation: 0, shape: 51 },
    { position: { z: -3 }, orientation: 0, shape: 1 },
    { position: { z: -3 }, orientation: 1, rotation: 1, shape: 16 },
    { position: { z: -3 }, orientation: 2, rotation: 3, shape: 20 },
    { position: { z: -3 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 5, rotation: 0, shape: 52 },
    { position: { z: -3 }, orientation: 5, rotation: 3, shape: 2 },
  ] as SurfaceDefinition[],
  pyramid2x2: [
    { orientation: 0, rotation: 3, shape: 11 },
    { orientation: 2, rotation: 0, shape: 33 },
    { orientation: 3, shape: 1 },
    { orientation: 4, rotation: 2, shape: 9 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 12 },
    { position: { z: -1 }, orientation: 2, rotation: 0, shape: 34 },
    { position: { z: -1 }, orientation: 3, rotation: 1, shape: 2 },
    { position: { x: -1 }, orientation: 2, rotation: 0, shape: 34 },
    { position: { x: -1 }, orientation: 3, rotation: 1, shape: 2 },
    { position: { x: -1 }, orientation: 4, rotation: 2, shape: 10 },
  ] as SurfaceDefinition[],
  pyramid2x4: [
    { orientation: 0, rotation: 3, shape: 17 },
    { orientation: 2, rotation: 0, shape: 35 },
    { orientation: 3, shape: 1 },
    { orientation: 4, rotation: 2, shape: 9 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 18 },
    { position: { z: -1 }, orientation: 2, rotation: 0, shape: 36 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -2 }, orientation: 0, rotation: 3, shape: 19 },
    { position: { z: -2 }, orientation: 2, rotation: 0, shape: 37 },
    { position: { z: -2 }, orientation: 3, rotation: 1, shape: 9 },
    { position: { z: -3 }, orientation: 0, rotation: 3, shape: 20 },
    { position: { z: -3 }, orientation: 2, rotation: 0, shape: 38 },
    { position: { z: -3 }, orientation: 3, rotation: 1, shape: 10 },
    { position: { x: -1 }, orientation: 2, rotation: 0, shape: 37 },
    { position: { x: -1 }, orientation: 3, rotation: 1, shape: 9 },
    { position: { x: -1 }, orientation: 4, rotation: 2, shape: 10 },
    { position: { x: -1, z: -1 }, orientation: 2, rotation: 0, shape: 38 },
    { position: { x: -1, z: -1 }, orientation: 3, rotation: 1, shape: 10 },
  ] as SurfaceDefinition[],
  pyramid4x4: [
    { orientation: 0, rotation: 3, shape: 17 },
    { orientation: 2, rotation: 0, shape: 43 },
    { orientation: 3, shape: 1 },
    { orientation: 4, rotation: 2, shape: 13 },
    { position: { z: -1 }, orientation: 0, rotation: 3, shape: 18 },
    { position: { z: -1 }, orientation: 2, rotation: 0, shape: 44 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -2 }, orientation: 0, rotation: 3, shape: 19 },
    { position: { z: -2 }, orientation: 2, rotation: 0, shape: 45 },
    { position: { z: -2 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 0, rotation: 3, shape: 20 },
    { position: { z: -3 }, orientation: 2, rotation: 0, shape: 46 },
    { position: { z: -3 }, orientation: 3, rotation: 1, shape: 2 },
    { position: { x: -1 }, orientation: 2, rotation: 0, shape: 44 },
    { position: { x: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1 }, orientation: 4, rotation: 2, shape: 14 },
    { position: { x: -1, z: -1 }, orientation: 2, rotation: 0, shape: 45 },
    { position: { x: -1, z: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -2 }, orientation: 2, rotation: 0, shape: 46 },
    { position: { x: -1, z: -2 }, orientation: 3, rotation: 1, shape: 2 },
    { position: { x: -2 }, orientation: 2, rotation: 0, shape: 45 },
    { position: { x: -2 }, orientation: 3, shape: 1 },
    { position: { x: -2 }, orientation: 4, rotation: 2, shape: 15 },
    { position: { x: -2, z: -1 }, orientation: 2, rotation: 0, shape: 46 },
    { position: { x: -2, z: -1 }, orientation: 3, rotation: 1, shape: 2 },
    { position: { x: -3 }, orientation: 2, rotation: 0, shape: 46 },
    { position: { x: -3 }, orientation: 3, rotation: 1, shape: 2 },
    { position: { x: -3 }, orientation: 4, rotation: 2, shape: 16 },
  ] as SurfaceDefinition[],
  invpyramid2x2: [
    { orientation: 0, shape: 1 },
    { orientation: 2, shape: 1 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { position: { z: -1 }, orientation: 0, shape: 1 },
    { position: { z: -1 }, orientation: 2, rotation: 0, shape: 54 },
    { position: { z: -1 }, orientation: 2, rotation: 2, shape: 2 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -1 }, orientation: 5, rotation: 0, shape: 11 },
    { position: { x: -1 }, orientation: 1, rotation: 1, shape: 9 },
    { position: { x: -1 }, orientation: 2, rotation: 0, shape: 54 },
    { position: { x: -1 }, orientation: 2, rotation: 2, shape: 2 },
    { position: { x: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1 }, orientation: 4, shape: 1 },
    { position: { x: -1, z: -1 }, orientation: 1, rotation: 1, shape: 10 },
    { position: { x: -1, z: -1 }, orientation: 2, rotation: 0, shape: 53 },
    { position: { x: -1, z: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -1 }, orientation: 5, rotation: 0, shape: 12 },
  ] as SurfaceDefinition[],
  invpyramid2x4: [
    { orientation: 0, shape: 1 },
    { orientation: 2, shape: 1 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { position: { z: -1 }, orientation: 0, shape: 1 },
    { position: { z: -1 }, orientation: 2, shape: 1 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -2 }, orientation: 0, shape: 1 },
    { position: { z: -2 }, orientation: 2, rotation: 0, shape: 58 },
    { position: { z: -2 }, orientation: 2, rotation: 3, shape: 11 },
    { position: { z: -2 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 0, shape: 1 },
    { position: { z: -3 }, orientation: 2, rotation: 0, shape: 57 },
    { position: { z: -3 }, orientation: 2, rotation: 3, shape: 12 },
    { position: { z: -3 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 5, rotation: 0, shape: 11 },
    { position: { x: -1 }, orientation: 1, rotation: 1, shape: 13 },
    { position: { x: -1 }, orientation: 2, rotation: 0, shape: 58 },
    { position: { x: -1 }, orientation: 2, rotation: 3, shape: 11 },
    { position: { x: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1 }, orientation: 4, shape: 1 },
    { position: { x: -1, z: -1 }, orientation: 1, rotation: 1, shape: 14 },
    { position: { x: -1, z: -1 }, orientation: 2, rotation: 0, shape: 57 },
    { position: { x: -1, z: -1 }, orientation: 2, rotation: 3, shape: 12 },
    { position: { x: -1, z: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -2 }, orientation: 1, rotation: 1, shape: 15 },
    { position: { x: -1, z: -2 }, orientation: 2, rotation: 0, shape: 56 },
    { position: { x: -1, z: -2 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -3 }, orientation: 1, rotation: 1, shape: 16 },
    { position: { x: -1, z: -3 }, orientation: 2, rotation: 0, shape: 55 },
    { position: { x: -1, z: -3 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -3 }, orientation: 5, rotation: 0, shape: 12 },
  ] as SurfaceDefinition[],
  invpyramid4x4: [
    { orientation: 0, shape: 1 },
    { orientation: 2, shape: 1 },
    { orientation: 3, shape: 1 },
    { orientation: 4, shape: 1 },
    { position: { z: -1 }, orientation: 0, shape: 1 },
    { position: { z: -1 }, orientation: 2, shape: 1 },
    { position: { z: -1 }, orientation: 3, shape: 1 },
    { position: { z: -2 }, orientation: 0, shape: 1 },
    { position: { z: -2 }, orientation: 2, shape: 1 },
    { position: { z: -2 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 0, shape: 1 },
    { position: { z: -3 }, orientation: 2, rotation: 0, shape: 66 },
    { position: { z: -3 }, orientation: 2, rotation: 2, shape: 2 },
    { position: { z: -3 }, orientation: 3, shape: 1 },
    { position: { z: -3 }, orientation: 5, rotation: 0, shape: 17 },
    { position: { x: -1 }, orientation: 2, shape: 1 },
    { position: { x: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1 }, orientation: 4, shape: 1 },
    { position: { x: -1, z: -1 }, orientation: 2, shape: 1 },
    { position: { x: -1, z: -1 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -2 }, orientation: 2, rotation: 0, shape: 66 },
    { position: { x: -1, z: -2 }, orientation: 2, rotation: 2, shape: 2 },
    { position: { x: -1, z: -2 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -3 }, orientation: 2, rotation: 0, shape: 65 },
    { position: { x: -1, z: -3 }, orientation: 3, shape: 1 },
    { position: { x: -1, z: -3 }, orientation: 5, rotation: 0, shape: 18 },
    { position: { x: -2 }, orientation: 2, shape: 1 },
    { position: { x: -2 }, orientation: 3, shape: 1 },
    { position: { x: -2 }, orientation: 4, shape: 1 },
    { position: { x: -2, z: -1 }, orientation: 2, rotation: 0, shape: 66 },
    { position: { x: -2, z: -1 }, orientation: 2, rotation: 2, shape: 2 },
    { position: { x: -2, z: -1 }, orientation: 3, shape: 1 },
    { position: { x: -2, z: -2 }, orientation: 2, rotation: 0, shape: 65 },
    { position: { x: -2, z: -2 }, orientation: 3, shape: 1 },
    { position: { x: -2, z: -3 }, orientation: 2, rotation: 0, shape: 64 },
    { position: { x: -2, z: -3 }, orientation: 3, shape: 1 },
    { position: { x: -2, z: -3 }, orientation: 5, rotation: 0, shape: 19 },
    { position: { x: -3 }, orientation: 1, rotation: 1, shape: 13 },
    { position: { x: -3 }, orientation: 2, rotation: 0, shape: 66 },
    { position: { x: -3 }, orientation: 2, rotation: 2, shape: 2 },
    { position: { x: -3 }, orientation: 3, shape: 1 },
    { position: { x: -3 }, orientation: 4, shape: 1 },
    { position: { x: -3, z: -1 }, orientation: 1, rotation: 1, shape: 14 },
    { position: { x: -3, z: -1 }, orientation: 2, rotation: 0, shape: 65 },
    { position: { x: -3, z: -1 }, orientation: 3, shape: 1 },
    { position: { x: -3, z: -2 }, orientation: 1, rotation: 1, shape: 15 },
    { position: { x: -3, z: -2 }, orientation: 2, rotation: 0, shape: 64 },
    { position: { x: -3, z: -2 }, orientation: 3, shape: 1 },
    { position: { x: -3, z: -3 }, orientation: 1, rotation: 1, shape: 16 },
    { position: { x: -3, z: -3 }, orientation: 2, rotation: 0, shape: 63 },
    { position: { x: -3, z: -3 }, orientation: 3, shape: 1 },
    { position: { x: -3, z: -3 }, orientation: 5, rotation: 0, shape: 20 },
  ] as SurfaceDefinition[],
} as const;
//{ orientation: , rotation: , shape:  },

export type BasicBlockType = keyof typeof BLOCK_SURFACE_DEFINITIONS;

export function getSurfaces(block: DeepReadonly<BasicBlock>): BasicSurface[] {
  const surfaces = BLOCK_SURFACE_DEFINITIONS[block.type];

  const { x, y, z } = block.position;
  return surfaces.map((s) => {
    return {
      ...s,
      rotation: s.rotation ?? 0,
      position: {
        x: x + (s.position?.x ?? 0),
        y: y + (s.position?.y ?? 0),
        z: z + (s.position?.z ?? 0),
      },
    };
  });
}
